### ISSUE TITLE
Don't have access to Roswell, can this be built into CLI form via SBCL?

### ISSUE THREAD

**Issue by johnabs** [yitzchak/cl-indentify#3]
Hi yitzchak,

Sorry this is a bit of a pain to ask, but my distro doesn't provide a simple way for me to get Roswell (I'm on gnu guix), yet your package is being provided there, but without the CLI app from what I can tell. 

I'm not sure if you are the person who built the versions for Guix, but I'm curious if you happen to know a way to get this project compiled to the cli version but via SBCL. 

If you don't want to worry about this weird edge case, I'll see if I can figure it out and submit a PR, but some input to point me in the right direction at least would be super helpful, as I've not made binaries with lisp before.

Thanks for taking the time to read this, I appreciate it!

Best,
John

**Comment by yitzchak** [comment]
Using quicklisp you can do the following:

```
sbcl --non-interactive --eval "(ql:quickload :cl-indentify/cli)" --eval "(apply #'indentify/cli:main (uiop:command-line-arguments))" -- code/packages.lisp
```

For non-quicklisp installations you probably just need to use `asdf:load-system` instead.

**Comment by johnabs** [comment]
This seems to work, thanks for the help, I really appreciate it!
